version: '3.7'

services:

  server:
    image: cloud-server
    container_name: 'cloud-server'
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - /pg_data:/var/lib/postgresql/data
    container_name: 'db_postgres'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"